### PR TITLE
[jak1] Improve the Swedish translations

### PR DESCRIPTION
**Pull request by fabjan**
Hello!

It's fun to see this project making such great progress. I'm a big fan of the original game.

I don't know who MysticGamer23 is or how long this community has been developing, but I noticed the Swedish translations had room for improvement:

* There are some spelling errors
* Compounds are written as one word in Swedish, but the current translation does not do this
* Some words and names were not translated and that made inflection hard and unnatural

So, I made some changes and share them in this PR in the hope that we can combine the works somehow. Of course, whether my PR even constitutes improvements is pretty subjective. Are there perhaps other Swedes already in the community that would like to review my changes and help me iterate?

Sorry for the change being a bit huge, but many of the translations cross over each other so I found it hard to do this in smaller pieces. At least it's not a risky change (I assume). **I don't expect a swift review**, just wanted to share what I think are improvements for this game I really like.

## Notes

`evilbro-misty-end` has no translation, but `fishermans-boat-ride-to-village1-alt` also has the same text, what gives?

Some characters have particular dialects or ways of speaking: Jak's uncle, the fisherman, the farmer, Billy etc. and their uniqueness is not captured very well I think, neither in the current translation or my updates. Perhaps something to be adressed in the future, I don't have any good ideas.

### Pronouns

Sage is now translated as "visman" instead of "vis man". "Vis man" makes one think of the three wise men. Visman is a old-timey word with a meaning very close to "sage": https://www.saob.se/artikel/?unik=V_1341-0012.xQ0Z-0005#U_V1341_17399

I kept "Precursor" as is, given how important the term is in the game. It is a bit odd to use, but Swedish gamers would probably find "Föregångare" rather silly. "Prekursor" as the current translation says is a nonsense translation that only really makes the spelling more natural.

I changed all instances of "de" and "dem" to "dom", which I think is a better fit for dialogue in a game like this.

### Creature names

Lurker is not translated as "lurk". Not quite the same meaning but it is possible to use in Swedish dialogue. https://www.saob.se/artikel/?seek=lurk&pz=1#U_L1039_197300

Yakow is now translated as "jako", and inflected like "ko" (jak is yak, ko is cow in Swedish)

Flut Flut is now translated as "flut-flut", making it a compound simplifies the dialogue I think, but there is still room for improvement. For example, maybe a better Swedish translation would be "flaxflax"?

### Names of things

Power cell is now translated as "kraftcell", a better translation than "energicell", I think.

Teleporter gate is now translated as "teleportal", a portmanteau. A straight translation would be "teleporterport" which is a bit of a mouthful, and "teleporter" is not really a Swedish word anyway.

Like for "precursor", I kept "eco" the same (as the current translation does) but added hyphens where it is used in compounds.

### Place names

| old | new | why change (in my opinion)|
|:-|:-|:-|
|Död Mans Dal|Död Mans Klyfta| More accurate
|Eld Dalen|Eldravinen| More accurate
|Laval Tuben|Lavatunneln| More accurate, and tube is a rather odd Swedish word
|Sentinel Stranden| Väktarstranden| A better compound, and translated
|Skout flugor|Spejarflugor| A proper compound, and a translation
|Tända mullvadar|Blixtmullvadar| It literally means lightning mole, instead of "lit mole"

### Daxter

Daxter has a very casual language, and every time he says "eco stuff", the current Swedish translation says (literally) "echo thing". Thing is countable, stuff is not. I replaced this with "eco-grejset" or "eco-mojset", words I think better convey his manner of speaking.

## Testing

I have unfortunately not yet been able to build this on my little MacBook Air to verify, and I'm not sure what kind of testing would be necessary for translation changes. Are there limits to line lengths? I made sure not to add or reorder any lines.

### CODE REVIEW

**Comment by xTVaser** [comment]
Thanks for taking the time to improve them and the lengthy write-up explaining your reasoning.  Some problems like:
> Compounds are written as one word in Swedish, but the current translation does not do this
and
> There are some spelling errors

_may_ have been my fault -- `MysticGamer23` did the translations with the aid of a screenreader and such.  So I had to convert them from a microsoft word file into our raw text format -- so things like extra whitespace may have slipped past my conversion.

For future reference you can submit alternative translations here https://crowdin.com/project/opengoal/sv-SE instead of having to make a GitHub PR if you find that easier.

> Are there limits to line lengths?

There are line length limits, and there's a tool built into the game to detect too-long of lines.  But if you are on a macbook you can't really use that -- someone else can probably look into that eventually on your behalf.

@himham-jak Pinging you in-case you wanted to weigh in on any of these changes. Being as I speak zero swedish and the changes sound good, I'll probably merge this as part of this month's release.

**Comment by xTVaser** [comment]
ok to test

**Comment by fabjan** [comment]
Thanks for the fast response!

Ah, the crowdin.com translation tool is maybe easier to use than my approach (edit in a diff view comparing with the en_US file, and look at git diff for my Swedish changes). I hope I didn't make things more complicated for the project by opening a GitHub PR for translations if that's not how you normally roll. I have no problems working in GitHub so it's all right by me 👍 

Without any additional tooling I can at least take a look at my changes and check if any dialogue lines became longer than before. Or if the limit is for example the same for all dialogue I can check the length of all new lines.

**Comment by xTVaser** [comment]
Nah it shouldn't cause any issues.

There's unlikely to be other Swedish changes on Crowdin to be in-flight (not yet pulled into this repo).  But in general it would be the preferred spot in-case multiple people were working on it at the same time.

It's also nice because the strings can be marked explicitly as being proof-read.  Which since I gather you've basically looked over everything (correct me if I'm wrong) -- I'll probably mark all current Swedish translations as being proof-read after this merges

**Comment by ManDude** [comment]
> `evilbro-misty-end` has no translation, but `fishermans-boat-ride-to-village1-alt` also has the same text, what gives?

`evilbro-misty-end` is a temporary placeholder cutscene and `fishermans-boat-ride-to-village1-alt` is the full version of that cutscene that the developers intended to make. In the end however neither go used in-game. It's still translatable because why not? Maybe someone else can use them in the future.

**Comment by fabjan** [comment]
Yes, I read through all of the lines, bottom to top for some reason.

I'm still confused by the two identical (almost, aside from some ellipses) dialogues `evilbro-misty-end` and `fishermans-boat-ride-to-village1-alt`. I noticed the issue in several other languages. The lines only make sense for an evil brother and not a fisherman on a boat.

**Comment by ManDude** [comment]
Oh also, for general lore terms like "Precursor" it would be wise to check what they have officially been translated as first - The Lost Frontier is playable in Swedish (both audio and text) so you can check how that game did it.

**Comment by ManDude** [comment]
> I'm still confused by the two identical (almost, aside from some ellipses) dialogues `evilbro-misty-end` and `fishermans-boat-ride-to-village1-alt`. I noticed the issue in several other languages. The lines only make sense for an evil brother and not a fisherman on a boat.

`fishermans-boat-ride-to-village1-alt`is this cutscene: https://www.youtube.com/watch?v=SGZtXltUaMU

That's the internal name for the cutscene. The fisherman's boat plays that cutscene, and it's a cutscene where you ride from misty island to sandover (village1).

**Comment by fabjan** [comment]
@ManDude awesome!

I found https://www.youtube.com/watch?v=eYwlEassVR4 which I guess has all the cutscenes. They made the same choice I made for translating "Eco" and using it in compounds. Clicking around on the timeline I can't find any mentions of Precursors though, was that perhaps not really in the story of that game?

**Comment by Computerfan23** [comment]
Hi there!
I am the person called mysticgamer23 over on discord. I am a blind gamer and live in sweden. Snce i am blind, i rely on using screen reader and text to speech.
I did the original translation for jak 1 into swedish. I had to do all translations in a word document since there was no other easy way for me to do it. I got the original text file sent to me and had it open beside the document where i did the translation. Since i use a screen reader, i may have missed certain things.
I am glad you looked over this and could proof read it.

**Comment by ManDude** [comment]
> @ManDude awesome!
> 
> I found https://www.youtube.com/watch?v=eYwlEassVR4 which I guess has all the cutscenes. They made the same choice I made for translating "Eco" and using it in compounds. Clicking around on the timeline I can't find any mentions of Precursors though, was that perhaps not really in the story of that game?

Daxter at least mentions a "Precursor bear" and "Precursor game system" during the credits. There's also the term "Precursor orb" used for... well, you know.

**Comment by ManDude** [comment]
image
"Precursor orbs" translated as "Precursororber"

**Comment by fabjan** [comment]
Hello @Computerfan23, thanks for the hästjobb! It would be great if you had the time to look at my diff from your original and then we can discuss if something is better backed out or can be improved otherwise. Ah, Discord, figures. I tried googling the nickname after seeing the initial commit of the translation but found nothing.

Given you put in the original effort I'd really like your input, I opened this PR as a place to have some discussion. Don't feel like you need to rush it for my sake. It took me several days to have the energy to go through all this. If you prefer to give feedback on Discord over GitHub, I can find my way onto the server.

@ManDude a veritable walking Daxter encyclopedia. Yeah he says "Precursor-nalle" (bear) so they went with the same solution as for "Eco".

**Comment by Computerfan23** [comment]
Hi @fabjam!
Sure, i could take a look at what you changed. How would i be able to see your changes?
No worries, it took me roughly a week to translate all the subtitle lines.

**Comment by fabjan** [comment]
In a PR like this, there is an [overview of the changes](https://github.com/open-goal/jak-project/pull/2770/files#diff-2447364b96d0b316773ebf40e7eef810c3348c467fbfab808655de7e987d9ac7) but I have no idea how usable GitHub is with a screen reader. The diff is big so it doesn't show unless you click the "Load diff" link for the first file there.

I pulled out my changes from your original of the in-game dialogue manually in a diff format and uploaded as [a "gist" here on GitHub](https://gist.github.com/fabjan/ffe612951ffbb8337ed42ef7c02d8823#file-subtitle_lines_sv-se-json-diff)

[Here is a "gist"  of my changes to the "custom text"](
https://gist.github.com/fabjan/ffe612951ffbb8337ed42ef7c02d8823#file-game_custom_text_sv-se-json-diff)

I don't know how readable a diff file is if you are not a programmer by trade. Lines starting with a minus sign were removed, lines starting with a plus sign were added, lines with no prefix are unchanged and there to give context. Let me know if it reads like crap and I can try some other format. (I tried with the builtin macOS voice over and it was not very usable)

If you can imagine a way you would like to read how a text file full of dialogue like this has been changed I can try to massage the diff-file to be more readable. For example, the default diff format has a tendency to group blocks of changes together, but you would perhaps rather hear every line one by one as it was changed (especially for subtitles where the lines are not really free flowing as other kinds of text can be).

**Comment by fabjan** [comment]
I made up a diff format that might be better fit for more linear reading (like with a screen reader), in this file, every other line is from the current version and my new version. Each line is prefixed with "FÖRE:" or "EFTER:" depending on which version it's from. [Here is a 2000 line file describing each of the 1000 changed lines of dialogue](https://gist.githubusercontent.com/fabjan/ffe612951ffbb8337ed42ef7c02d8823/raw/7486eddcb1b30fc4ec3ed0aeffe3a64b822f7eb5/subtitle_lines_sv-SE.json.skillnad)

**Comment by Computerfan23** [comment]
Yeah, i tried to view the file, but it did not work. Github is not that user friendly if you use a screen reader.
Is there a possibility you could put it as a document or a word file? And maybe put parenthesis around the ones which are the changes?
Would that work?

**Comment by fabjan** [comment]
@Computerfan23 I don't have Word but looks like TextEdit can create Word documents so I can try that. I need a bit more specifics than "parenthesis around changes", however. Note that there are 962 lines changed (445 unchanged).

If a piece of dialogue is for example 10 lines, and I changed 3 of them, how would you like ot read that? Would you like to read the unchanged lines for context, and then the changed lines in parenthesis? Would you like to read the previous/current version of each changed line somehow as well? I reached out in DM on Discord, maybe some back and forth there will be easier than on GitHub. But we can continue here if you prefer.

Här kommer ett exempel på en ändrad dialog (18 rader), jag presenterar hela före och sedan hela efter ändringar.

Före (18 rader):
    "geologist-introduction": [
      "NI TVÅ SER UT SOM ETT PAR PÅLITLIGA PERSONER.",
      "JAG HAR ETT PÅGÅENDE FORSKNINGSPROJEKT,",
      "OCH NI SKULLE KANSKE KUNNA HJÄLPA MIG.",
      "HÖR UPP HÄR, VI ÄR DE SOM ÄR UTE PÅ ETT STORT UPPDRAG.",
      "VI BER DIG OM HJÄLP.",
      "I SÅ FALL, SÅ SKULLE VI KANSKE KUNNA HJÄLPA VARANDRA.",
      "JAG HAR HÅLLT PÅ MED ATT STUDERA TÄNDA MULLVADARS GRÄVNINGSSÄTT",
      "I PREKURSOR DALEN BREDVID VÅR BY UNDER MÅNGA ÅR.",
      "MEN NU HAR DE DÄR HEMSKA LURKERS SKRÄMT UPP MULLVADARNA TILL YTAN!",
      "OCH EFTERSOM DE ÄR BLINDA SOM FLADDERMÖSS, SÅ KAN DE INTE HITTA VÄGEN TILLBAKA NER UNDER MARKEN.",
      "OM NI SKULLE KUNNA FÖSA TILLBAKA DE NER I SINA UTGRÄVDA TUNLAR,",
      "SÅ SKULLE NI KANSKE KUNNA RÄDDA DERAS LIV.",
      "JAG HAR EN ENERGI CELL HÄR SOM SÄGER ATT NI KAN LYCKAS GÖRA DET.",
      "VISST, TÄNDA MULLVADAR... OM VI BRYR OSS.",
      "KANSKE FÖR TVÅ ENERGI CELLER!",
      "BRA FÖRSÖK. MEN JAG SKULLE VARA VILLIG ATT GÖRA MIG AV MED YTTERLIGARE EN ENERGI CELL",
      "IFALL NI SKULLE KOMMA HIT MED 90 PREKURSOR KULOR FÖR MIN FORSKNINGS UTRUSTNING.",
      "LÅTER DET RÄTTVIST?"
    ],

Efter (18 rader):
    "geologist-introduction": [
      "NI TVÅ SER UT SOM ETT PAR KAPABLA PERSONER.",
      "JAG HÅLLER PÅ MED ETT FORSKNINGSPROJEKT,",
      "OCH NI SKULLE KANSKE KUNNA HJÄLPA MIG.",
      "HÖRRU, VI ÄR DOM SOM ÄR UTE PÅ ETT STORT UPPDRAG.",
      "VI BER DIG OM HJÄLP.",
      "JAHA, VI KAN KANSKE HJÄLPA VARANDRA.",
      "JAG HAR STUDERAT BLIXTMULLVADARS GRÄVVANOR",
      "I PRECURSOR-DALEN BREDVID VÅR BY UNDER FLERA ÅR.",
      "MEN NU HAR DOM DÄR HEMSKA LURKARNA SKRÄMT MULLVADARNA UPP TILL YTAN!",
      "OCH EFTERSOM DOM ÄR BLINDA SOM FLADDERMÖSS SÅ KAN DOM INTE HITTA TILLBAKA NER UNDER MARKEN.",
      "OM NI SKULLE KUNNA FÖSA TILLBAKA DOM NER I SINA GRÄVTUNNLAR,",
      "SÅ SKULLE NI KANSKE KUNNA RÄDDA DERAS LIV.",
      "JAG HAR EN KRAFTCELL HÄR SOM SÄGER ATT NI KAN LYCKAS GÖRA DET.",
      "VISST, BLIXTMULLVADAR... OM VI BRYR OSS.",
      "KANSKE FÖR TVÅ KRAFTCELLER!",
      "BRA FÖRSÖK. MEN JAG SKULLE VARA VILLIG ATT GÖRA MIG AV MED YTTERLIGARE EN KRAFTCELL",
      "OM NI SKULLE KOMMA HIT MED 90 PRECURSOR KULOR FÖR MIN FORSKNINGSUTRUSTNING.",
      "LÅTER DET RÄTTVIST?"
    ],

Här kommer ett exempel från delen "hints" (5 rader), först före ändringar och sedan efter ändringar.

Före (5 rader):
    "asstvb04": [
      "BRA, NI HAR LYCKATS SAMLA IHOP TILLRÄCKLIGT MÅNGA ENERGI CELLER FÖR ATT GE ENERGI ÅT MIN VÄRMESKÖLD!",
      "MÖT MIG VID INGÅNGEN TILL ELD FLODBÄDDEN",
      "GENOM ATT KLÄTTRA UPP FÖR KLIPPAN BAKOM BONDENS HUS.",
      "TA MED ER ENERGI CELLERNA, OCH SKYND HIT!",
      "MIN FAR SÄGER ATT HAN HAR SETT FLER LURKERS RUNOMKRING HÄR!"
    ],

Efter (5 rader):
    "asstvb04": [
      "BRA, NI HAR LYCKATS SAMLA IHOP TILLRÄCKLIGT MÅNGA KRAFTCELLER FÖR ATT GE ENERGI ÅT MIN VÄRMESKÖLD!",
      "MÖT MIG VID INGÅNGEN TILL ELDRAVINEN",
      "GENOM ATT KLÄTTRA UPP FÖR KLIPPAN BAKOM BONDENS HUS.",
      "TA MED ER KRAFTCELLERNA, OCH SKYNDA HIT!",
      "MIN FAR SÄGER ATT HAN HAR SETT FLER LURKAR I KROKARNA!"
    ],

**Comment by fabjan** [comment]
I've been in contact on Discord with Computerfan23 for a bit today, in order to describe and share the changes in a manner better than what GitHub provides.

I'm in no rush to see this translation being merged so I'd really like them to be able to give input on my changes, if they like. At least a couple of days if needed given the work that was put in for their first version.

If you see other Swedish changes appearing in Crowdin wanting to get integrated, I can deal with any merge conflicts afterwards in this PR.

**Comment by xTVaser** [comment]
kk, I'll drop the PR down to draft status -- mark it ready for review once it's ready to go.

**Comment by Computerfan23** [comment]
Hi! During the last couple of days, i have been reading through the improved translations made by fabjan. We fixed several errors after i spotted them.
I have now finished reading the translation and i am confident in reporting that everything looks good and i am happy with the improvements.
So i am happy to give this the go ahead and give green light.
Thanks very much to fabjan and all the great work!

**Comment by fabjan** [comment]
No thank _you_ for the translation @Computerfan23! This is but a small improvement on things, even if it's 1000+ lines changed 😅

**Review by xTVaser — APPROVED** [review]
Looks good to me, you two did the proof-reading and the new linter which checks for invalid characters is passing.

**Pull request merged**
