### PR TITLE
utf8: fix locale mis-handling on linux

### LINKED ISSUE #1688: OpenGoal extractor is not working on Linux since  v0.17
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The decompiler fails on my NTSC iso file since version 0.17. 

### How To Reproduce

Run the extractor on Linux with the PAL or the NTSC iso file.   The process always fails: 

2022-07-20 19:19:43:139] [info] Extracting Z6TAIL.DUP...
[2022-07-20 19:19:44:871] [info] Detected Game Metadata:
[2022-07-20 19:19:44:871] [info] 	Detected - Jak & Daxter™: The Precursor Legacy (Black Label)
[2022-07-20 19:19:44:871] [info] 	Region - NTSC-U
[2022-07-20 19:19:44:871] [info] 	Serial - SCUS-97124
[2022-07-20 19:19:44:871] [info] 	Uses Decompiler Config - jak1_ntsc_black_label
[2022-07-20 19:20:16:658] [info] -Loading types...
[2022-07-20 19:20:16:841] [error] -100. was supposed to be an number, but isn't when parsing decompiler type file:
decompiler/config/all-types.gc:16776
(deftype sprite-frame-data (structure)
 ^

[2022-07-20 19:20:16:864] [error] Error during decompile: std::exception

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The extractor should complete the task

### Operating System

Linux  , Manjaro or Ubuntu LTS

### OpenGOAL Version

0.1.20

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

### PR DESCRIPTION
**Pull request by xTVaser**
Hopefully this resolves things, should probably test prior to merging on linux.  I confirmed utf-8 args are still getting into windows properly.

Closes #1688

### CODE REVIEW

**Review by water111 — APPROVED** [review]
Tested on linux, seems to work. Thanks!

**Comment by ZazaLeNounours** [comment]
Tested on my Steam Deck, it still doesn't work with version 1.21, with the same ISO and same settings (Deck OS is in French, if that matters) that still work just fine on 1.16.

**Comment by xTVaser** [comment]
@ZazaLeNounours Please make an issue with logs so we can figure out the problem

**Comment by ZazaLeNounours** [comment]
@xTVaser sure, let me know where I can find them (I'm no Linux power user _at all_) and I'll be happy to share.

**Pull request merged**
