### PR TITLE
Add menu bar toggle

### PR DESCRIPTION
**Pull request by SortAnon**
- Toggle the ImGui menu bar by pressing Alt
- Hides the menu bar by default in fullscreen and borderless modes

### CODE REVIEW

**Comment by ManDude** [comment]
Jeez people really hate the damn bar...

**Comment by xTVaser** [comment]
This also triggers when switching windows via Alt+Tab which i could see being annoying while developing (possibly also during normal usage) -- I don't really have a better key suggestion in mind.

**Comment by NickDriscoll** [comment]
Why not just ESC?

**Comment by Zedb0T** [comment]
ESC by default is already pound to 1st controller start

**Comment by NickDriscoll** [comment]
Huh. For me it's ENTER.

**Comment by Zedb0T** [comment]
Ah maybe that got changed when they updated the keybindings

**Comment by SortAnon** [comment]
> This also triggers when switching windows via Alt+Tab
Good point. I've changed it to trigger on release if the window is focused. That works on KDE, and likely Windows as well.

**Review by xTVaser — APPROVED** [review]

**Pull request merged**
