### PR TITLE
Spanish subtitles (WIP)

### PR DESCRIPTION
**Pull request by jml95**
Spanish subtitles (WIP):
-intro
-sidekick
-village1 (uncompleted, subtitles missing in english)
-oracle (subtitles missing in english, rest completed)
-beach (daxter hints included) 
-jungle (daxter hints and keira hint included)
-misty (daxter hints included)
-firecanyon (daxter hints included)
-citadel (daxter hints included)

There are still some dialogues missing in english. I tried including them myself in spanish but everytime i did that, I got a compilation error.

**UPDATE (29th of June):** 

Spanish subtitles UPDATES (WIP):
-intro (all the scenes and hints availiable at this moment in english have been included)
-sidekick (all the scenes and hints availiable at this moment in english have been included)
-village1 (all the scenes and hints availiable at this moment in english have been included)
-oracle (all the scenes and hints availiable at this moment in english have been included)
-beach (all the scenes and hints availiable at this moment in english have been included)
-jungle (all the scenes and hints availiable at this moment in english have been included)
-misty (all the scenes and hints availiable at this moment in english have been included)
-firecanyon (all the scenes and hints availiable at this moment in english have been included)
-citadel (all the scenes and hints availiable at this moment in english have been included)

No more updates in the subtitles until more of them are made in english first.

### CODE REVIEW

**Comment by towai** [comment]
what's the compilation error? can you elaborate on this?
also, i see that you've copied several cutscenes and hints in english into spanish without changes, which probably shouldn't be there (and are present in game_subtitle_en.gd, so i don't think they're related to your last point) until you're actually ready to subtitle them for spanish.

**Comment by jml95** [comment]
Let me try to explain myself better: what i did was directly downloading the latest release of Opengoal for Windows, and then I modified the "game_subtitle_es.gd" file directly: I copied all the subtitle lines from the english file "game_subtitle_en.gd" and pasted them into the spanish file, and from there I started editing the spanish subtitles. That is why there are still lots of cutscenes or hints written in english and unmodified. These will be changed later, but i'm using them as a guide, even though sometimes i had to synchronize the subtitles  .

What happened to me was that, for example, I tried adding new scenes from the oracle that were missing in the english file. Then i saved it and i grabbed my Jak and Daxter iso into the "extractor.exe" application, but the process failed in these cases. 
I also worked on the death scenes where Daxter says something to Jak before restarting from the last checkpoint. When I introduced them into the "game_subtitle_es.gd" file and then I tried to make the extraction process I got the same error.

I suppose that my mistake is that I thought I could add new scenes directly into "game_subtitle_en.gd" and the extract process would work. Now that I installed Visual Studio and I can open the "subtitle-groups.json" file I think that first i have to "register" every new scene that i want to introduce in the game in the appropiate group. Am I right?

**Comment by OngakuGH** [comment]
Hi jml95, I'm Ongaku from the italian translation team.
We already completed all the subtitles that are avaiable in english too and I think that is the problem you currently have.
As you know, there are different subtitle groups inside "game_subtitle_es.gd", used to identify and search the text for the game, the subtitle editor and for yourself (if you edit directly from the file).
You currently can not add new subtitles because you need to create new scenes/groups and connect them to the cutscenes/hints of the game.
What I suggest you to do is to currently prepare in another personal file the translated subtitles and wait for the english subtitle to be updated.
Create new scenes/groups now before the english subtitles could be confusing for the programmers and translators.

To avoid spam, we can keep the discussion on discord (Ongaku#2358) or inside Opengoal discord server.

**Comment by towai** [comment]
you don't have to know anything about programming to contribute what you can, don't worry!

there's a subtitle editor in the game but it's not the greatest experience right now if you're adding scenes that don't exist - and I think using it to its fullest requires you to launch the game in debug mode. however, it has built-in functionality to add subtitles to one language using another as a base, and I think you should start there. it's in the top bar that shows up if you press Alt (or might already be there when you start the game, I dunno).

plus, doesn't TPL actually have a Spanish dub? so hopefully, you're basing your translations on the lines spoken in-game, the process of which is also something the functionality of the subtitle editor would help speed up and make more painless, at least for hints. what I mean by that is, the subtitle editor has a button next to each scene that will make the game play it immediately, so you don't have to get the hint to come up through playing the game. sadly each cutscene requires custom code in order to make the game do this, but most of the ones in the first few areas have that.

it's true that if you edit the game_subtitle_es.gd or game_subtitle_en.gd manually and add a scene that isn't already in any subtitle file, you would have to also add it to subtitle-groups.json manually, which is another good reason to use the subtitle editor, as it does that for you. if you need more help with using it than is in the interface, there's people in the discord who would be more than willing to help.

**Comment by jml95** [comment]
> Hi jml95, I'm Ongaku from the italian translation team. We already completed all the subtitles that are avaiable in english too and I think that is the problem you currently have. As you know, there are different subtitle groups inside "game_subtitle_es.gd", used to identify and search the text for the game, the subtitle editor and for yourself (if you edit directly from the file). You currently can not add new subtitles because you need to create new scenes/groups and connect them to the cutscenes/hints of the game. What I suggest you to do is to currently prepare in another personal file the translated subtitles and wait for the english subtitle to be updated. Create new scenes/groups now before the english subtitles could be confusing for the programmers and translators.
> 
> To avoid spam, we can keep the discussion on discord (Ongaku#2358) or inside Opengoal discord server.

Hi there OngakuGH! Then what i'm going to focus first is in translating the rest of subtitles that are currently availiable until they add more. And I am also going to follow your advice and prepare all the new lines in another document (i have included the death scenes and the oracle missing dialogues there already). Thank you so much for your help. Anything else I need, i will contact you directly in discord to avoid spam.

**Comment by jml95** [comment]
> you don't have to know anything about programming to contribute what you can, don't worry!
> 
> there's a subtitle editor in the game but it's not the greatest experience right now if you're adding scenes that don't existin any subtitle file (I have a PR in the works that deals with a lot of this and it went from painful to breezy in my experience) - and I think using it to its fullest requires you to launch the game in debug mode. however, it has built-in functionality to add subtitles to one language using another as a base, and I think you should start there. it's in the top bar that shows up if you press Alt (or might already be there when you start the game, I dunno).
> 
> plus, doesn't TPL actually have a Spanish dub? so hopefully, you're basing your translations on the lines spoken in-game, the process of which is also something the functionality of the subtitle editor would help speed up and make more painless, at least for hints. what I mean by that is, the subtitle editor has a button next to each scene that will make the game play it immediately, so you don't have to get the hint to come up through playing the game. sadly each cutscene requires custom code in order to make the game do this, but most of the ones in the first few areas have that.
> 
> it's true that if you edit the game_subtitle_es.gd or game_subtitle_en.gd manually and add a scene that isn't already in any subtitle file, you would have to also add it to subtitle-groups.json manually, which is another good reason to use the subtitle editor, as it does that for you. if you need more help with using it than is in the interface, there's people in the discord who would be more than willing to help.

Hi towai! Yes! I've seen that subtitle editor but I don't know how to make it work properly because I don't know what steps I have to follow in order to conect the REPL. But what I know is how to enter in the game's debug mode. That is how I was able to test the cutscenes with the new subtitles I've been adding. 

And...yes! TPL has Spanish dub, and sure, what the characters say is exactly what is going into the subtitles i am making. I was able to extract all the spanish audio files from the .VAG file from my Jak and Daxter copy with a program named "PSound. So I can play the lines as many times as I want in order to get the subtitles written correctly.

As I said to OngakuGH, what I think I am going to do for now, is to make the spanish subtitles that are already availiable in english. In that way I will not get any kind of errors afterwards. Unless I can find the way to connect the REPL and be able to use the subtitles editor properly. Maybe I'll ask for help in the discord channel.

Thank you so much for all your help. I really appreciate it.

**Pull request closed without merging**
