### PR TITLE
[game] 150fps fixes

### PR DESCRIPTION
**Pull request by Brent-Hickey**
This fixes https://github.com/open-goal/jak-project/issues/1492
And it addresses some of https://github.com/open-goal/jak-project/issues/1499

Unfortunately the 150fps issues seem to all be case-by-case fixes (so its helpful for people to keep tracking them). They either have an animation that needs adjusted, did frame-based math, or relied on the seconds-per-frame as part of math where it probably wasn't supposed to be used. Usually when it related to animations + velocities. 

- Slow walk after roll has been fixed, I don't think it was supposed to look at seconds-per-frame here because the velocity it checks is already scaled
- Jak walking animation I removed the seconds-per-frame and I think it's correct for a similar reason. Are any other jak animations feeling sped up/slowed down?
- Eye blink was counting a certain number of frames so that's fixed
- Had the math wrong for the physics tick (ocean + scrollable textures) making them slightly slower than they should be
- The misty boat is a spooled animation that needed slowed so that's fixed. It also has that table of velocities for controlling it that are probably wrong but i wont worry about that 
- Same thing for gondola ride, should be fixed
- Zoomer has a lot of animations and velocities tied to seconds-per-frame so it doesn't surprise me that something is off here. But I don't know enough to determine which ones are even slow cause the zoomer generally feels good to me so i'll need someone to really tell me what's wrong about the zoomer

### CODE REVIEW

**Comment by Zedb0T** [comment]
Pretty sure the cooldown between going into goggles is way faster. Also the aiming when you enter the goggles

**Comment by Hat-Kid** [comment]
Similar to the roll bug, I've observed a slow walk after a normal jump, but not always. That may be fixed already if the roll bug is fixed.

I've also noticed of Jak's idle animations was slowed down considerably.

**Comment by Brent-Hickey** [comment]
Which idle animation? I had to hard code each idle animation by name to be slowed down, it's possible I'm slowing one down that I shouldn't

**Comment by Zedb0T** [comment]
The wind on jak seems sped up

**Comment by Hat-Kid** [comment]
> Yep slowness after normal jumps is also fixed here. Which idle animation? I had to hard code each idle animation by name to be slowed down, it's possible I'm slowing one down that I shouldn't

It was the one with Daxter balancing on Jak's head, but I just noticed that it was only slowed when I locked the framerate to 60, it plays fine in 150 fps.

**Comment by NolanHewitt** [comment]
The Eco Meter (when eco is running low) seems to flash too fast at 150 fps.

**Review by water111 — APPROVED** [review]
Looks good! If there end up being a lot of these fixes, you might want to make some macro for `(or (= (-> *setting-control* current video-mode) '150fps) (= (-> *setting-control* current video-mode) '100fps)`. Maybe something like `(high-fps-mode?)`.

**Pull request merged**
