### PR TITLE
remove unused nix build files

### PR DESCRIPTION
**Pull request by water111**
unless somebody wants to maintain these and add tests.

### CODE REVIEW

**Comment by water111** [comment]
will close #1327

**Comment by xTVaser** [comment]
We'll want to cleanup the readme that references this as well https://github.com/open-goal/jak-project#with-nix

But yeah I don't think anyone actively working on the project uses this or maintains it, makes sense to get rid of it.

**Comment by heph2** [comment]
Maybe who made the PR which add them, can say something about this. @bb010g 
An option would be to create a derivation and port them to nixpkgs, but idk

**Comment by bb010g** [comment]
I can update these this weekend.

**Comment by xTVaser** [comment]
Should we just move forward with this removal?  Removing what is presently broken doesn't prevent someone from contributing a fix.

**Comment by water111** [comment]
Sure. I'll remove it this friday unless I hear that somebody has actually used it, or somebody is working on a fix.  If we don't have tests or any contributors using nix, I don't know that it's worth it to maintain.

**Pull request merged**
