### PR TITLE
Disable hints if you restart in debug mode?

### PR DESCRIPTION
**Pull request by himham-jak**
pls this would make testing so much less annoying

### CODE REVIEW

**Comment by ManDude** [comment]
why not just turn them off in the settings? or load a savefile with them off.

**Comment by himham-jak** [comment]
Most of the time when I'm testing, I'm not in a save file at all. Going through and testing features can mean rebooting dozens of times. Turning off hints each time is a chore

**Comment by dallmeyer** [comment]
I will say it's a little frustrating having to turn them off manually very time the game reboots while you're testing stuff. I would love to just `task boot-game` and not have to deal with this.

Alternatively, if the play-hints setting could be saved globally vs per save file, that would solve this headache too

**Comment by ManDude** [comment]
Nothing stops you from keeping this change locally, but I'm not sure there's really any point to merging to master. The behavior is unintuitive unless you see this single line of code. Conversely, I tested various things with hints so I'd rather keep them enabled. And I'd rather not flip flop settings around like this.

You can also load a file with just 4 button presses that you can chain very quickly.

**Pull request closed without merging**
