### PR TITLE
jak2: overlord rework

### LINKED ISSUE #2522: no orb reward after talker speeches (side missions)

### LINKED ISSUE #2545: No announcer / intercom audio
likely requires streaming audio

### LINKED ISSUE #2546: Guard conversations are not working
Likely requires streaming audio

### LINKED ISSUE #2547: no vehicle tutorial

### LINKED ISSUE #2548: city-krew-delivery: no torn audio

### LINKED ISSUE #2549: meet-brutter - missing dialogue and sfx

### LINKED ISSUE #2550: Bridge collapse has no sound
likely requires streaming audio, or is the fault of the stream playback hack

https://user-images.githubusercontent.com/89345505/221420391-1e2d8b24-d23b-4ea4-a5aa-c711478ebaa9.mp4

### LINKED ISSUE #2551: Odd delay before cutscene is started
doubled thing is probably tie visibility flags, which are not supported by the PC renderer (https://github.com/open-goal/jak-project/issues/2133).

Doubled thing is resolved - Zed

delay is possibly related to the `gui-control`/streaming hacks. It might be something else, but it's probably not worth looking at yet.

### LINKED ISSUE #2552: Sig's gun is forever jammed near the end of the escort and juicers spawn indefinitely
Cause is `gui-control` stuff again

### LINKED ISSUE #2553: atoll-battle -- no ashelin audio

### LINKED ISSUE #2554: No Red security pass text when starting tank fight
Doesnt pop up after delivery to krew either - Scatter gun acquired. going to assume this is an issue across the whole game, and not open more issues for text missing

### LINKED ISSUE #2555: Tutorial audio skipped for now

### LINKED ISSUE #2556: Metal head scare animation has no sound

### LINKED ISSUE #2557: No krew dialogue

### LINKED ISSUE #2558: No platform collapse sound

### LINKED ISSUE #2559: wells - no daxter audio

### LINKED ISSUE #2560: No sound when rhino breaks rocks / when platform is ejected
likely related to streaming audio

### LINKED ISSUE #2561: No sound during moving platform bridge collapse animation
likely related to streaming audio

### LINKED ISSUE #2562: dialogue currently skipped for jetboard training

### LINKED ISSUE #2563: destroy-ship - no dialogue at the end of the missioin

### LINKED ISSUE #2564: No completion dialogue for scouts mission

### LINKED ISSUE #2565: seal piece - button cutscenes are broken
`gui-control` stuff

### LINKED ISSUE #2566: escort - no dialogue

### LINKED ISSUE #2567: escort - they get stuck on the first elevator

### LINKED ISSUE #2568: Boulder in Daxter chase doesn't move or spawns at origin

### LINKED ISSUE #2569: no baron dialogue

### LINKED ISSUE #2570: boss kill cutscene doesnt play

### LINKED ISSUE #2571: No sound during cutscenes

### PR DESCRIPTION
**Pull request by xTVaser**
Fixes #2545
Fixes #2546
Fixes #2547
Fixes #2548
Fixes #2549
Fixes #2550
Fixes #2551
Fixes #2552
Fixes #2553
Fixes #2554
Fixes #2555
Fixes #2556
Fixes #2557
Fixes #2558
Fixes #2559
Fixes #2560
Fixes #2561
Fixes #2562
Fixes #2563
Fixes #2564
Fixes #2565
Fixes #2567
Fixes #2566
Fixes #2568
Fixes #2569
Fixes #2570
Fixes #2522
Fixes #2571

### CODE REVIEW

**Comment by water111** [comment]
New issues
- crackle when daxter's audio finishes in fortress
- hitching audio when fortress airlock opens
- crackles when entering protect kor cutscene
- audio spam on dark jak lightning
- crash at the end of fortress dump, logs:
`
cmd's pitch is 3763, 0
key OOF: 0 (1600)
got nax: 26374
terminate from Isothread 2
key OOF: 0 (1600)
release 400
termina removing cityv082 (2)
ERROR: SCRIPT: could not spawn task-manager for node #<game-task-node-info city-vehicle-training-map open @ #x1abe194> level ctywide
`
- gui-control is still blocking avalanche in mountain temple
- crash when entering `mountain-insert-items` cutscene, no decent logs to share
- forest scouts make no noise when dying
- crumbling platforms in ruins don't crumble correctly
- possibly quiet audio in ashlein fight resolution cutscene (or possibly related to general issues with audio getting quiet after a while)

**Comment by xTVaser** [comment]
Codacy called out a bunch of lints as usual.  But also there are a few critical errors that seem legit -- maybe they are sources of original bugs we could iron out?
image
image

**Comment by ManDude** [comment]
1. As Codacy suspects, it's a redundant check. No divide by 0 can occur there.
2. Correct, there may be a null deref here.
3. This OOB access is fine, it's just grabbing the address past the array and gets corrected later.
4. This OOB access is fine, it's just grabbing the address past the array and gets corrected later.
5. Not sure how bad this is but the string is only used for debugging. Can probably still be fixed though.

**Comment by ManDude** [comment]
Introduces bug where idle animations don't work and Jak just freezes in place.

**Comment by ManDude** [comment]
A lot of the bad sound issues seem to happen when there are two stereo tracks queued up.

**Comment by water111** [comment]
> Codacy called out a bunch of lints as usual. But also there are a few critical errors that seem legit -- maybe they are sources of original bugs we could iron out?

Yeah, this definitely needs a cleanup pass for codacy/compiler warnings and general organization. It's not ready to merge. As far as I can tell these warnings end up being ok but I will definitely take a closer look.

**Pull request merged**
