### PR TITLE
clean-up `control-info`

### PR DESCRIPTION
**Pull request by ManDude**
Names the fields and fixes some decomp errors.

### CODE REVIEW

**Comment by ManDude** [comment]
shut up, bot

**Comment by xTVaser** [comment]
add to whitelist

**Review by water111 — COMMENTED** [review]
Changes/names all look good to me, hanks for cleaning this stuff up. I think you are missing some .gc file changes.

**Comment by ManDude** [comment]
I know, I wanted to see if anyone could help figuring out the remaining ones. :)

**Comment by water111** [comment]
ah ok, I'll take a look soon

**Comment by xTVaser** [comment]
This PR has so many merge conflicts and no activity for a year.  Probably best to reopen when it becomes a priority again.

**Pull request closed without merging**
