### PR TITLE
French subtitle_meta_fr-FR.json

### PR DESCRIPTION
**Pull request by RoyalForgotten**
French subtitles meta

### CODE REVIEW

**Comment by xTVaser** [comment]
you should combine both file changes into a single PR, if you don't know how let me know and I can do it for you.

**Comment by RoyalForgotten** [comment]
Yes, i have no idea how to do

**Comment by xTVaser** [comment]
@RoyalForgotten Combined changes here https://github.com/open-goal/jak-project/pull/3259 also saw you had a third branch that updated the custom-text files.  I assumed you wanted these included as well, let me know if that was a bad assumption.

**Comment by RoyalForgotten** [comment]
> @RoyalForgotten Combined changes here #3259 also saw you had a third branch that updated the custom-text files. I assumed you wanted these included as well, let me know if that was a bad assumption.

Yes indeed, but when i saw that you told me that it is possible to combine several files into one, i looked for how to do it but i found nothing, if you want, you can also adding it. (i imagine you can also do this without posting a PR ?)

**Pull request closed without merging**
