### PR TITLE
Spanish subtitles (WIP)

### PR DESCRIPTION
**Pull request by jml95**
All the subtitles that are currently availiable in english have been included in the spanish version. Could this be merged in future releases?

-intro
-sidekick
-oracle
-training
-village1
-beach
-jungle
-misty
-firecanyon
-village2
-swamp
-rolling
-sunken
-ogre
-village3
-snowy
-spidercave
-lavatube
-citadel
-finalboss

### CODE REVIEW

**Comment by ManDude** [comment]
Follow the same procedure as in #1502 

- Add the language to the progress menu so users can select it.
- Add the language to the debug menu (optional).
- Use the built-in subtitle debugger (L3+Start) to check if every line fits within 2 on-screen lines *at 4x3 aspect ratio*. (Use "Check all lines" then look at the console.)
- Check if any hints or movies are missing.

**Comment by Hat-Kid** [comment]
Since #1704 is not merged yet, I went ahead and ran these subtitles through the debugger, [these are all the bad lines that need to be split up](https://pastebin.com/pq80mdeL).

Spanish is already in the subtitle language option in the progress menu and in the debug menu, so you don't need to add it there.

**Comment by ManDude** [comment]
Oh, you're right - I added it lol. Yeah, do the other stuff I guess.

**Comment by GKnight95** [comment]
Hey everyone, is there any chance I could help you with the translation? First time using GitHub so not sure to post this comment here but please, let me know! Spanish is my native language btw, thank you!

**Comment by xsm2** [comment]
Maybe I'm wrong, but I think this commit was already fixed and merged in this PR: https://github.com/open-goal/jak-project/pull/1828 (look at the last commit https://github.com/open-goal/jak-project/pull/1828/commits/07b8088c6a7713686addaaeabd9019659a735ffe)

If I'm not wrong, the only thing left for Spanish to be complete would be the game_text (the addittional texts that were added for the port's new menus, like the graphic settings) which are still not translated, but I don't think this PR should stay open as it doesn't include them and it has been nearly three months since the last update.

**Pull request closed without merging**
