### PR TITLE
jak 1 polish translation - typo fix

### PR DESCRIPTION
**Pull request by rafalekkB**
i literally just noticed one level name had a typo

### CODE REVIEW

**Comment by rafalekkB** [comment]
also subtitle translation 88% done atm id love for one of the admins to check crowdin like tomorrow or something

**Comment by xTVaser** [comment]
I sync the changes from crowdin before cutting each monthly release, so there isn't much for us to look at (i don't think any of us speak polish)  But great job on almost finishing it all!

**Comment by rafalekkB** [comment]
> I sync the changes from crowdin before cutting each monthly release, so there isn't much for us to look at (i don't think any of us speak polish) But great job on almost finishing it all!

Thanks! Was a real joy to go through the code and strings of one of my all time favourite games!
BTW I've messaged you on discord in regards to some outdated strings you uploaded to Polish on crowding, but no clue if you actually have your dm's open. Could you take a look? @xTVaser

**Comment by ManDude** [comment]
you should make a new branch off of `master` and then cherry pick the new commits onto that branch.

**Pull request closed without merging**
